# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Domodedovo' do
	use_frameworks!
	pod 'MaterialComponents', '~>124.1.1'
  pod 'Alamofire', '~>5.4.1'
  pod 'DropDown'
end
